const { Router } = require('express');
const { z } = require('zod');
const controller = require('./alerts.controller');
const { validate, jsonBodyParser } = require('../security/input-validation');
const { listAlertsQuerySchema, alertIdParamSchema, resolveAlertSchema } = require('./alerts.validation');
const { requireAuth, requireRole } = require('../middleware/auth');
const { ROLES } = require('../config/constants');

const router = Router();
const emptyBodySchema = z.object({}).strict();

router.use(jsonBodyParser());
router.use(requireAuth);

// Alerts are system-generated by the anomaly engine (src/anomaly) — there is
// no POST / here. This module is read + triage (acknowledge/resolve) only.
router.get(
  '/',
  requireRole([ROLES.ADMIN, ROLES.BOARD, ROLES.AUDITOR, ROLES.CENTER]),
  validate(listAlertsQuerySchema, 'query'),
  controller.list
);
router.get(
  '/:id',
  validate(alertIdParamSchema, 'params'),
  requireRole([ROLES.ADMIN, ROLES.BOARD, ROLES.AUDITOR, ROLES.CENTER]),
  controller.getOne
);
router.post(
  '/:id/acknowledge',
  validate(alertIdParamSchema, 'params'),
  requireRole([ROLES.ADMIN, ROLES.BOARD, ROLES.AUDITOR]),
  validate(emptyBodySchema),
  controller.acknowledge
);
router.post(
  '/:id/resolve',
  validate(alertIdParamSchema, 'params'),
  requireRole([ROLES.ADMIN, ROLES.BOARD, ROLES.AUDITOR]),
  validate(resolveAlertSchema),
  controller.resolve
);

module.exports = router;
