const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  BOARD: 'BOARD',
  COURIER: 'COURIER',
  CENTER: 'CENTER',
  INVIGILATOR: 'INVIGILATOR',
  AUDITOR: 'AUDITOR',
});

const ROLE_VALUES = Object.values(ROLES);

const CUSTODY_STEPS = Object.freeze({
  CREATED: 'CREATED',
  HANDOVER_TO_COURIER: 'HANDOVER_TO_COURIER',
  ARRIVED_AT_CENTER: 'ARRIVED_AT_CENTER',
  STORED_IN_VAULT: 'STORED_IN_VAULT',
  HANDOVER_TO_EXAM_HALL: 'HANDOVER_TO_EXAM_HALL',
  OPENED_FOR_EXAM: 'OPENED_FOR_EXAM',
  COMPLETED: 'COMPLETED',
});

const CUSTODY_STEP_ORDER = [
  CUSTODY_STEPS.CREATED,
  CUSTODY_STEPS.HANDOVER_TO_COURIER,
  CUSTODY_STEPS.ARRIVED_AT_CENTER,
  CUSTODY_STEPS.STORED_IN_VAULT,
  CUSTODY_STEPS.HANDOVER_TO_EXAM_HALL,
  CUSTODY_STEPS.OPENED_FOR_EXAM,
  CUSTODY_STEPS.COMPLETED,
];

const PAPER_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  IN_TRANSIT: 'IN_TRANSIT',
  SECURED: 'SECURED',
  OPENED: 'OPENED',
  COMPLETED: 'COMPLETED',
  FLAGGED: 'FLAGGED',
});

const ALERT_SEVERITY = Object.freeze({
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
});

const ALERT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  RESOLVED: 'RESOLVED',
});

const QUESTION_DIFFICULTY = Object.freeze({
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
});

const QUESTION_DIFFICULTY_VALUES = Object.values(QUESTION_DIFFICULTY);

module.exports = {
  ROLES,
  ROLE_VALUES,
  CUSTODY_STEPS,
  CUSTODY_STEP_ORDER,
  PAPER_STATUS,
  ALERT_SEVERITY,
  ALERT_STATUS,
  QUESTION_DIFFICULTY,
  QUESTION_DIFFICULTY_VALUES,
};
